seed: 42
paths:
  train_csv: data/train.csv
  val_csv: data/val.csv
  checkpoints: models/checkpoints/real_model_artifacts
training:
  epochs: 40
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0   # (optional; ignored by current script)
