seed: 42
paths:
  test_csv: data/test.csv
  eval_out: outputs/eval
model:
  checkpoint: models/checkpoints/real_model_artifacts/best_model_enet.pth

generator:
  checkpoint: models/wgan_gp/wgan_gp_checkpoint.pt
  z_dim: 100
  num_classes: 2
  num_normal: 555
  num_anomalous: 555
  batch_size: 32
  output_dir: outputs/samples
